In [1]:
# Face Recognition

# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
from tensorflow.keras.models import load_model
import numpy as np
import pickle

from sklearn import svm


Using TensorFlow backend.


In [2]:

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [3]:

from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')

In [4]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face



<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-4-39f7dd144c4e>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [5]:
# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
count=0
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='rohith'
        elif(pred[0][1]>0.5):
            name='manohar'
        elif(pred[0][2]>0.5):
            name='madhan'
        else:
            name='unknown'
            count=count+1
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        print(count)
        #takepi(count)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

0
[[0.0000000e+00 1.0000000e+00 1.5840553e-29 0.0000000e+00]]
0
[[0.0000000e+00 1.0000000e+00 2.9430296e-33 0.0000000e+00]]
0
0
0
0
0
0
0
0
0
0
0
[[3.115901e-34 1.000000e+00 6.637815e-25 0.000000e+00]]
0
0
0
0
0
0
0
0
0
0
0
0
[[0.0000000e+00 1.0000000e+00 9.9891415e-37 0.0000000e+00]]
0
0
0
0
0
0
0
0
0
0
0
0
0
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
0
0
0
0
[[0. 1. 0. 0.]]
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
[[3.4921017e-37 1.0000000e+00 4.1099776e-38 0.0000000e+00]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[2.1084114e-35 1.0000000e+00 1.6003672e-24 0.0000000e+00]]
[[5.3401098e-32 1.0000000e+00 1.3163602e-25 0.0000000e+00]]
[[0. 1. 0. 0.]]
[[2.0184693e-37 1.0000000e+00 0.0000000e+00 0.0000000e+00]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0.000000e+00 1.000000e+00 1.186628e-38 0.000000e+00]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0.000000e+00 1.000000e+00 7.609913e-33 0.000000e+00]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
0
[[0.0000000e+00 1.0000000e+00 1.6199

enter2
